version: "3"
services:
  cloudtorrent:
    image: uesteibar/cloudtorrent-armhf
    volumes:
      - '${DOWNLOADS_FOLDER-/media/mediacenter/downloads}:/downloads'
    ports:
      - "4000:3000"
    networks:
      - webnet

networks:
  webnet:
