version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Europe/Bucharest
      - PLEX_CLAIM=
      - PLEX_UID=1000
      - PLEX_GID=1000
    hostname: xxx
    volumes:
      - '~/mediacenter/plex_config:/config'
      - '${DOWNLOADS_FOLDER-~/mediacenter/downloads}:/data'
    ports:
      - "3001:32400"
      - "3000:3000"
    networks:
      - webnet
  transmission:
    image: linuxserver/transmission
    volumes:
      - '~/mediacenter/transmission_config:/config'
      - '${DOWNLOADS_FOLDER-~/mediacenter/downloads}:/downloads'
    ports:
      - "5001:9091"
    networks:
      - webnet
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    volumes:
      - '~/mediacenter/sonarr_config:/config'
      - '${DOWNLOADS_FOLDER-~/mediacenter/downloads}:/downloads'
      - '${DOWNLOADS_FOLDER-~/mediacenter/downloads}/series:/tv'
    ports:
      - "4001:8989"
    networks:
      - webnet
  nginx:
    image: nginx
    restart: always
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
